export enum Type {
    SELECT = 'SELECT',
    INSERT = 'INSERT',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    CREATE_TABLE = 'CREATE TABLE',
    DROP_TABLE = 'DROP TABLE',
    ALTER_TABLE = 'ALTER TABLE',
    CREATE_INDEX = 'CREATE INDEX',
    DROP_INDEX = 'DROP INDEX',
    BEGIN_TRANSACTION = 'BEGIN TRANSACTION',
    COMMIT = 'COMMIT',
    ROLLBACK = 'ROLLBACK',
    VACUUM = 'VACUUM',
    REINDEX = 'REINDEX',
    ANALYZE = 'ANALYZE',
    PRAGMA = 'PRAGMA',
}

export interface Statement {
    type: Type;
}